apiVersion: v1
description: A OpenLDAP Chart for Kubernetes
name: icp-openldap
version: 0.1.5
keywords: [ldap]
home: https://www.openldap.ort
sources:
  - https://github.com/openldap/openldap
maintainers:
  - name: Hans Kristian Moen
    email: hans.kristian.moen@gmail.com
engine: gotpl
